version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - export S3_BUCKET={S3バケット名}
      - aws cloudformation package --template-file template.yaml --s3-bucket $S3_BUCKET --output-template-file packaged.yaml
artifacts:
  type: zip
  files:
    - template.yaml
    - packaged.yaml